### ISSUE TITLE
Relation to splunk/vault-plugin-secrets-gitlab

### ISSUE THREAD

**Issue by in0rdr** [ilijamt/vault-plugin-secrets-gitlab#113]
I stumbled upon this project and was wondering how it relates and/or compares to [splunk/vault-plugin-secrets-gitlab](https://github.com/splunk/vault-plugin-secrets-gitlab).

While trying both plugins, I already found~~s~~ subtle differences in the configuration. For instance, I cannot configure `auto_rotate_token` and `auto_rotate_before` with the Splunk version.

Would be interested if you see more differences and maybe you already did an assessment of other plugins in this space?

**Comment by ilijamt** [comment]
When we were evaluating, a lot of the functionality was not there, still isn't. 
you are unable to issue, project, group tokens, as well as service account tokens.

**Comment by in0rdr** [comment]
Hi @ilijamt thanks a lot for that explanation, it's really helpful. Feel free to close the issue
