### ISSUE TITLE
Support Trigger Tokens for projects

### ISSUE THREAD

**Issue by Shocktrooper** [ilijamt/vault-plugin-secrets-gitlab#138]
One of the token types that is missing is a pipeline trigger token.  

I do not want to give alternate tokens with API access to other projects which is an alternative to this but I do want to allow said projects to kick off a pipeline in the downstream project without having access to code or other things in said project.

Other tokens/access that work but give too much access:
- Personal Access tokens with API scope
- Project Access tokens with API scipe
- Group Access tokens with API scope
- CICD job token that inherits the permissions of the person who kicked off the job.
- Developer access to downstream project

References:
- https://docs.gitlab.com/ee/ci/triggers/
- https://docs.gitlab.com/ee/api/pipeline_triggers.html
- https://docs.gitlab.com/ee/security/tokens/index.html

**Comment by ilijamt** [comment]
I'll need to take a look if this can be integrated. 

Can you provide some full examples of how would you use it?

**Comment by Shocktrooper** [comment]
Sure!
- One thing I want to do is let upstream projects kick off a specific downstream project without direct access via a users personal permissions or via project tokens that give too many permissions to the triggering project as I do not want the upstream project to have code access.  This would allow allowed projects to request a temporary token to the downstream project regardless of the users permissions and without needing a token with expanded permissions to kick off a pipeline
- Another would be for external systems to kick off a pipeline in GitLab without manually provisioning specific per project tokens that are static.  For instance if I had a service now workflow that updated a system and some GitLab projects are dependent on that change I can have the service now workflow request a temporary token to kick off the pipeline instead of something static that needs to be rotated and also expires at the end of its life where someone needs to remember to do so

**Comment by ilijamt** [comment]
I've released a new version, v0.7.1

- Gitlab Pipeline Project Trigger Tokens - https://docs.gitlab.com/ee/api/pipeline_triggers.html
- Gitlab Group/Project Deploy Tokens - https://docs.gitlab.com/ee/user/project/deploy_tokens

Can you give it a try and let me know how it goes?

**Comment by ilijamt** [comment]
Please reopen if you have any issues.
