### ISSUE TITLE
don't return token on READ to gitlab/config

### ISSUE THREAD

**Issue by TJM** [ilijamt/vault-plugin-secrets-gitlab#62]
The token value should be treated as _sensitive_ and not returned when a read request is set to gitlab/config.

**Comment by ilijamt** [comment]
I will change it so it reports it that is a sensitive value.

**Comment by ilijamt** [comment]
This is fixed in https://github.com/ilijamt/vault-plugin-secrets-gitlab/commit/ded89f1b374f9f2ed7049c19d70cdbc4c5966cf0
