### ISSUE TITLE
Allow rotation of non-admin config tokens

### ISSUE THREAD

**Issue by TJM** [ilijamt/vault-plugin-secrets-gitlab#89]
Related to #68 

We have the need to use a non-admin service account PAT, but we cannot have it expiring. We would like to use the "rotation API" or at a minimum, the "user" API for creating an access token. We could have an option to use rotation API or maybe we could use it, by default, if the version is over the version where rotation API was added.

**Comment by cm3brian** [comment]
We have also encountered this issue when trying to rotate tokens in GitLab Cloud, any chance the MR can be progressed? it would be greatly appreciated

**Comment by ilijamt** [comment]
@cm3brian I've been busy adding tests against real Gitlab instance, as soon as I'm finished with that you'll have that functionality as well. Hopefully this will land in the next couple of weeks.

**Comment by cm3brian** [comment]
@ilijamt thank you so much for your efforts and moving this along. Both the progress on this and the plugin over all are greatly appreciated from our side!

**Comment by ilijamt** [comment]
Would you guys be willing to test it out? Here is the MR #97

**Comment by ilijamt** [comment]
@cm3brian @TJM I tried with a normal user on gitlab.com, and now you are able to rotate the tokens (also added some tests for this as well). Instead of creating a separate one, I just made it all rotation of the main token use their own endpoint for it. So no need to have two code paths.

**Comment by ilijamt** [comment]
Released with the new version v0.4.0

**Comment by TJM** [comment]
Thanks @ilijamt !! Sorry, my gitlab emails were going to the wrong place and I didn't see these.

**Comment by ilijamt** [comment]
@TJM is it all good now?
