### ISSUE TITLE
Naming convention of generated tokens

### ISSUE THREAD

**Issue by cm3brian** [ilijamt/vault-plugin-secrets-gitlab#99]
First, thank you for this project, it was exactly what we needed to backend `vault-secrets-operator` and fix the impact of the 16.x 1 year max token expiry that caught us out a few weeks back.

Now we have scaled up using this plugin with vault-secrets-operator, we are finding it difficult to easily understand the origin of all the tokens that have been generated. We find the naming convention far too generic to even understand how/where the tokens are in use.

This is an example of just one isolated area (single group) in our setup:
<img width="534" alt="image" src="https://github.com/user-attachments/assets/45a5d5e6-17fd-42b3-af9b-749eebe512a7">

We feel that there should be more options and/or a better default for this. Currently, it seems to be using the `token_type` property for naming which is honestly already known; as I am in that specific area already (project, group, user) looking at the token(s), so it's quite redundant. 

We feel an immediate improvement here would be using the role's path-slug/name instead of the role's type.
So instead of `vault-generated-group-access-token-* `
A token generated from a role such as  `gitlab/roles/group-api` with a prop of `name=group-api-role`
could either output `vault-generated-group-api-access-token-*` or `vault-generated-group-api-role-access-token-*`

Further, the ability to inject either a partially or wholly custom name at the time of creation would be great. In our specific use case, we can pass in params to the request (see: https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultdynamicsecretspec:~:text=be%20set%20to.-,params,-object%20(keys%3Astring) so it's not beyond us just giving a custom name from our IaC setup (this may be a niche use-case though).

**Comment by ilijamt** [comment]
The `name` property was supposed to be used for that purpose. The original plan was to base it on text/template, just never got around to it.

**Comment by ilijamt** [comment]
I’ll have some time to look at this next week.

**Comment by ilijamt** [comment]
This is already possible with https://github.com/ilijamt/vault-plugin-secrets-gitlab?tab=readme-ov-file#name
Can you also give it a test to see if it works properly and if it does, I can release it.

**Comment by cm3brian** [comment]
@ilijamt Thank you. Just to be clear here, by saying "already possible" this implies that with the current release being `v0.4.1` I should be able to do this, is this correct? 

Looking at the most recent commit (https://github.com/ilijamt/vault-plugin-secrets-gitlab/commit/a5d06b095d1f0ea96d8e96bc1daa12dd96f57f900), however, it appears that a code change may have been required for this enablement?

That being the case do I need to compile a beta version for manual deployment to test the latest code at main?

Please let me know (I'm not great with Go... not my forte)

**Comment by ilijamt** [comment]
Sorry I missed this, what I meant is to compile the version and run it. I'll release the current one soon, so you should be able to use it just follow the upgrade instructions.

**Comment by ilijamt** [comment]
Released under `v0.5.0`
